spring.application.name=simfat-backend
server.port=${SERVER_PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/simfat}

app.cors.frontend-url=${FRONTEND_URL:http://localhost:3000}

